### ISSUE TITLE
Question: How can I use for multiple columns on a single model?

### ISSUE THREAD

**Issue by binaryweavers** [spatie/laravel-schemaless-attributes#43]
Can I use this package for more than one columns on a single model. I tried using same way as explained but I am getting
`Error: Call to a member function all() on array`
for the second column.

**Comment by freekmurze** [comment]
This is currently not supported.

**Comment by sustained** [comment]
> You're also free to add as many schemaless attribute columns to your table as you want.
So the README is incorrect here, then?

**Comment by nathan-io** [comment]
The readme still says you can add multiple schemaless attribute columns, I was wondering if that had changed or otherwise if the readme could be updated to note that?

I was also mistakenly under the impression that the package supported multiple columns on a single table. I just discovered this issue while looking for examples of preparing the model with multiple columns.

Thank you!
